name: GitHub Actions Demo
on: [push]
jobs:
  Exploring:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo "This Action was triggered by ${{ github.event_name }} event"
  Building:
    needs: Exploring
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project ${{ secrets.MY_SECRET }}"
      - run: echo "Build complete"
  
  Checking:
    needs: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2