name: GitHub Actions Demo
on: [push]
jobs:
  Exploring:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo "This Action was triggered by ${{ github.event_name }} event"
  Building:
    needs: Exploring
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project"
      - run: echo "Build complete"
